---
- name: Установка DB
  apt:
    name:
      - postgresql
      - python3-psycopg2
    state: present
    update_cache: true

- name: Конфигурация DB
  shell: |
    echo "host replication all 0.0.0.0/0  md5" >> /etc/postgresql/*/main/pg_hba.conf
    echo "wal_level = replica" >> /etc/postgresql/*/main/postgresql.conf
    sed -i "s/local   all             all                                     peer/local   all             all                                     trust/" /etc/postgresql/*/main/pg_hba.conf
    sed -i "s/local   all             postgres                                peer/local   all             postgres                                trust/" /etc/postgresql/*/main/pg_hba.conf
    systemctl restart postgresql

- name: Добавление пользователя wikiuser
  become: false
  #become_user: postgres
  postgresql_user:
    db: my_wiki
    name: wikiuser
    password: 12345678
    priv: "ALL"
    state: present
    login_unix_socket: "/var/run/postgresql"
    login_user: postgres

- name: Добавление БД my_wiki
  become: false
  #become_user: postgres
  postgresql_db:
    name: my_wiki
    encoding: UTF8
    state: present
    login_unix_socket: "/var/run/postgresql"
    login_user: postgres

# - name: Добавляем новую ДБ
#   command: sudo -u postgres psql -c "CREATE DATABASE my_wiki WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'my_wiki')\gexec"

# - name: Добавляем нового пользователя
#   command: sudo -u postgres psql -c "CREATE USER wikiuser WITH PASSWORD '12345678';"

# - name: Назначение прав
#   command: sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE my_wiki to wikiuser WITH PASSWORD '12345678';"