---
- name: Добавление Zabbix репозитория
  shell: |
    wget https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.2+ubuntu24.04_all.deb
    sudo dpkg -i zabbix-release_latest_7.2+ubuntu24.04_all.deb

- name: Установка Zabbix
  apt:
    name:
      - zabbix-server-pgsql
      - zabbix-frontend-php
      - php8.3-pgsql
      - zabbix-nginx-conf
      - zabbix-sql-scripts
      - zabbix-agent2
    state: present
    update_cache: true

- name: Активация Zabbix сервера
  service:
    name: zabbix-server
    state: started
    enabled: true

- name: Активация Zabbix агента
  service:
    name: zabbix-agent2
    state: started
    enabled: true