---
- name: Установка DB
  apt:
    name: postgresql
    state: present
    update_cache: true

- name: Конфигурация DB
  shell: |
    echo "host replication all 0.0.0.0/0  md5" >> /etc/postgresql/*/main/pg_hba.conf
    echo "wal_level = replica" >> /etc/postgresql/*/main/postgresql.conf
    systemctl restart postgresql