---
- hosts: proxy
  become: True
  roles:
    - proxy

- hosts: backend
  become: True
  roles:
    - backend

- hosts: database
  become: True
  roles:
    - database

- hosts: zabbix
  become: True
  roles:
    - zabbix

- hosts: backup
  become: True
  roles:
    - backup

- hosts: all
  become: True
  roles:
    - zabbix-agent