---
- name: Установка Zabbix
  apt:
    name: zabbix-agent
    state: present
    update_cache: true

- name: Активация Zabbix агента
  service:
    name: zabbix-agent
    state: started
    enabled: true